services:
  - type: web
    name: dripmarket
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: WC_URL
        value: https://cms.dripmarketua.store
      - key: WC_KEY
        sync: false
      - key: WC_SECRET
        sync: false
